spring:
  application:
    name: tcc-api-performance
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/tccdb
    username: tcc_user
    password: tcc_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true

server:
  port: 8085

grpc:
  server:
    port: 9090
